# Generated by Django 4.1.3 on 2022-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
