# Generated by Django 4.1.3 on 2022-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_category_post_featured_post_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
