# Generated by Django 4.1.3 on 2022-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('en', 'enable'), ('de', 'disable'), ('da', 'draft')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
