# Generated by Django 4.1.3 on 2022-11-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_categories_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
    ]
